INSERT INTO public."dictionary" (id, "class", "name", "type", description) VALUES
('PLACE', 'type', 'Place', 'PERSON', 'A place'),
('REGION', 'type', 'Region', 'PERSON', 'A (multi) polygon feature of a particular region'),
('CITIZEN', 'protocol', 'Citizen', NULL, 'Citizen: when a member of the public contributes an observation'),
('UNSPECIFIED', 'type', 'Unspecified', NULL, NULL),
('HEAD_LENGTH', 'type', 'Head Length', 'MEASUREMENT', 'Measurement of head length'),
('PUBLIC', 'source', 'Public', NULL, 'Data obtained from the general public'),
('IMPORTED', 'source', 'Imported', NULL, 'Data obtained through a bulk import'),
('LIFE_STAGE', 'type', 'Life Stage', 'MEASUREMENT', 'Determination of an individual''s life stage'),
('TREATED', 'action', 'Treated', NULL, 'Conducting/applying a treatement to an individual'),
('TRANSPORTED', 'action', 'Transported', NULL, 'Moving an individual'),
('TAKEN', 'action', 'Taken', NULL, 'Taking a sample'),
('SEX', 'type', 'Sex', 'MEASUREMENT', 'Determination of an individual''s sex'),
('TARSUS_DEPTH', 'type', 'Tarsus Depth', 'MEASUREMENT', 'Measurement of tarsus depth'),
('OBSERVED', 'action', 'Observed', NULL, 'Observation of an individual'),
('MEASURED', 'action', 'Measured', NULL, 'Taking a measurement'),
('DETERMINED', 'action', 'Determined', NULL, 'Result of a measurement or sample'),
('DEPLOYED', 'action', 'Deployed', NULL, 'Addition of an identifier to an individual'),
('TARSUS_LENGTH', 'type', 'Tarsus Length', 'MEASUREMENT', 'Measurement of tarsus length'),
('MANUAL', 'source', 'Manual', NULL, 'Data manually entered into the database'),
('GROUP', 'protocol', 'Group', NULL, 'Group: when something concerns multiple Individuals'),
('BAND_COMBO', 'type', 'Band combo', 'OBJECT_IDENTIFIER', 'A collection of (related) bands'),
('INTERVENTION', 'protocol', 'Intervention', NULL, 'Intervention: when an action is done to an Individual'),
('MEASUREMENT', 'protocol', 'Measurement', NULL, 'Measurement: a value obtained from an Individual, or determined about an Individual'),
('MEDIA', 'protocol', 'Media', NULL, 'Media: when a media file (usually a photo) concerns a particular individual'),
('OBSERVATION', 'protocol', 'Observation', NULL, 'Observation: a non-invasive event collecting information about an Individual'),
('PERSON', 'protocol', 'Person', NULL, 'Person: when someone is involved in an Event'),
('SAMPLE', 'protocol', 'Sample', NULL, 'Sample: when something is obtained from an individual'),
('TRANSMITTER', 'type', 'Transmitter', 'OBJECT_IDENTIFIER', 'A transmitter'),
('MICROCHIP', 'type', 'Microchip', 'OBJECT_IDENTIFIER', 'A microchip'),
('LEAD', 'type', 'Lead (blood)', 'OBJECT_SAMPLE', 'A blood sample taken for lead analysis'),
('CAPTURED', 'action', 'Captured', NULL, 'Capture of individual'),
('TARSUS_WIDTH', 'type', 'Tarsus Width', 'MEASUREMENT', 'Measurement of tarsus width'),
('WEIGHT', 'type', 'Weight', 'MEASUREMENT', 'Measurement of weight'),
('DISTANCE', 'type', 'Sighted (distant)', 'OBSERVATION', 'Individual(s) sighted at a distance'),
('HEARD', 'type', 'Heard', 'OBSERVATION', 'Individual(s) heard'),
('MACHINE', 'type', 'Machine observation', 'OBSERVATION', 'Observation made by a machine (e.g. camera)'),
('RADIO_TRACKING', 'type', 'Radio tracking', 'OBSERVATION', 'Observation made by radio tracking'),
('SIGHTED', 'type', 'Sighted', 'OBSERVATION', 'Individual seen'),
('FEATHER', 'type', 'Feather', 'OBJECT_SAMPLE', 'A feather sample'),
('LYSIS', 'type', 'Lysis (blood)', 'OBJECT_SAMPLE', 'A blood sample taken for DNS analysis'),
('BANDER', 'type', 'Bander', 'PERSON', 'Person responsible for banding'),
('VITAMIN_D', 'type', 'Vitamin D (blood)', 'OBJECT_SAMPLE', 'A blood sample taken for blood analysis'),
('HOLDER', 'type', 'Holder', 'PERSON', 'Person responsible for holding'),
('ARRIVAL', 'type', 'Arrival', 'INTERVENTION', 'An individual arrives somewhere'),
('CONTRIBUTOR', 'type', 'Contributor', 'PERSON', 'Member of the general public'),
('IDENTIFIER', 'protocol', 'Identifier', NULL, 'Identifier: Addition/removal of identifying devices to an individual, implies capture'),
('OBJECT_SAMPLE', 'type', 'Sample', 'object', 'A sample obtained from an individual'),
('OBJECT_IDENTIFIER', 'type', 'Identifier', 'object', 'An object used to identify an individual'),
('OBSERVER', 'type', 'Observer', 'PERSON', 'Person responsible for observing'),
('CHECK', 'type', 'Health Check', 'INTERVENTION', 'A individual undergoes a general health check'),
('CHELATION', 'type', 'Chelation', 'INTERVENTION', 'An individual undergoes chelation therapy'),
('DEPARTURE', 'type', 'Departure', 'INTERVENTION', 'An individual departs somewhere'),
('BILL_LENGTH', 'type', 'Bill Length', 'MEASUREMENT', 'Measurement of bill length'),
('VET', 'type', 'Vet', 'PERSON', 'Person providing care to an individual'),
('AUTOMATED', 'source', 'Automated', NULL, 'Data obtained through an automated device');
