import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

import Header from "@/app/components/layout/Header";
import Footer from "@/app/components/layout/Footer";
import type { Database } from "@/types/supabase";

import "./global.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <Header session={session} />
        {children}
        <Footer session={session} />
      </body>
    </html>
  );
}
